### ISSUE TITLE
Question about Visualization GarmentCodeData using GarmentViewer

### ISSUE THREAD

**Issue by ZishengYePhD** [maria-korosteleva/GarmentCode#11]
Hi Maria,

I am trying to visualize and simulate garment patterns of GarmentCodeData(GCD) using GarmentViewer. As mentioned in this GarmentCode(GC) project, GCD should be loaded into Maya with ease. I modified `control_scale` related codes in `core.py` in Garment-Pattern-Generator to get some GCD data work, but still I met self-intersection problems from time to time.

My main guess is there are some issues in patterns where `control_scale[["type"]=="circle"` . Another issue is the translations and rotations are not compatible with pre-draping setup in Maya, e.g. I loaded one "pants" but it appears above the head of an average SMPL model. Just wondering if you have solved such issues? Thank you!

**Comment by maria-korosteleva** [comment]
Hi @ZishengYePhD

You should setup Maya to look for the code in the GarmentCode repo, here is the info: 
https://github.com/maria-korosteleva/GarmentCode/blob/main/docs/Installation.md#optional-installing-autodesk-mayaqualoth-garment-viewer-gui

There were a few changes compared to the Garment-Pattern-Generator, so using the old project won't work 

If the issues persist, please, share the example patterns and I will look into it

**Comment by maria-korosteleva** [comment]
I assume that it worked. Please, reopen if the problem persists
