### ISSUE TITLE
Feature Request: Combining Panels Post-Mirror Operation

### ISSUE THREAD

**Issue by fox2049** [maria-korosteleva/GarmentCode#13]
I would like to extend my gratitude for your work on pattern-making and garment simulation.

I believe you might have already noticed an issue concerning the mirrored panels in garment simulations. After performing a mirror operation, there is a seam between the two panels at the center. Could there be a possibility to combine these adjacent panels into a single pattern after mirroring? This approach would resemble a fold symmetry rather than a split, aligning more closely with the standards in the garment industry.

I've tried to create a new panel by manually copying the edges, interfaces, and stitches from the two original panels, but unfortunately, this method was not yet successful. Implementing this feature seems to be quite challenging.

It would be fantastic if you could consider this feature for integration in future updates.
![image](https://github.com/user-attachments/assets/cfba0f9f-9197-4ee0-aad5-53a86c490445)

**Comment by maria-korosteleva** [comment]
Hi @fox2049, thank you for your kind words!

You are right, this is a limitation of our framework, and it would be awesome to have this feature! 

However, this is a research prototype supporting our two recent papers -- GarmentCode and GarmentCodeData. Being an academic lab, we have limited resources for additional development, and we only can provide basic maintenance (questions/bugfixes). We cannot make any promises on future releases, but we will keep your suggestion in mind. 

We do welcome contributions, and will be happy to include new features developed by the community =)
