### ISSUE TITLE
Documentation update w.r.t. MAYA Garment Viewer

### ISSUE THREAD

**Issue by NagabhushanSN24** [maria-korosteleva/GarmentCode#14]
Hi,

I think some documentation is missing w.r.t. visualising sewing pattern in MAYA Garment viewer

1. Installation instructions point to a blob file and not the Instructions doc in main branch.
2. It directs user to add `./external` to `PYTHONPATH`. It looks like `./external` has been updated to `./pygarment`.
3. It would help to include the location of the garment viewer script: `./gui/maya_garmentviewer.py`

**Comment by maria-korosteleva** [comment]
Hi @NagabhushanSN24 

1. Yes, installation instructions point to Github web version of files for link stability (e.g. being accessible from `pygarment` page on PyPI) 
2. and 3. Which documentation file are you referring to? Both questions are addressed in the documentation provided with GarmentCode: [docs/Running_Maya_Qualoth.md](https://github.com/maria-korosteleva/GarmentCode/blob/main/docs/Running_Maya_Qualoth.md )
