### ISSUE TITLE
Need help to understanding specification.json

### ISSUE THREAD

**Issue by machffud** [maria-korosteleva/GarmentCode#19]
My objective is to utilize the 3D rendering feature of Nvidia-Warp that you created by using my own specification.json as input. I am aware that the format of my specification.json differs slightly from yours, and I have attempted to adjust it, but I keep getting the same rendering result as my previous post.

Here are a few things I'd like to clarify:

Is specification.json sufficient as the sole input for Nvidia-Warp 3D rendering? (I am using the same default body as you.)
What are the essential fields in your specification.json? Even when I tried modifying fields like panel_name, label_body, label_endpoints, and type_curvature, the rendered output remained the same.
Thank you for your help!

**Comment by maria-korosteleva** [comment]
1) Our wrapper around Nvidia-Warp requires the specification file, body mesh and body measurements. So yes, if you use the same base model as we do, you only need to add a json specification file

2) All the elements of JSON file are essential for their own purpose. They control the geometry of the panels (most of the fields, including curvature type), connectivity (stitch fields). The "label" fields are using in simulation process to apply some of the special constraints and ensure the best result that can be achieved with the input pattern (sometime the falling of a garment is inevitable despite the best efforts). Panel names are used as references inside the specification (e.g. in stitch description). They are also consistent across garment samples with different parameters, which is useful when working with large collection of patterns like in GarmentCodeData 

Refer to the answers in #18 for some general guidance on what you can do with garments that fall down =)
