### ISSUE TITLE
Design params for the fantastical designs in GarmentCode

### ISSUE THREAD

**Issue by LSQsjtu** [maria-korosteleva/GarmentCode#23]
Due to my limited knowledge of garment design, I found it challenging to replicate certain fantastical designs in GarmentCode. For instance, when trying to recreate the shoulder in the images below, I struggled to achieve the desired **puff sleeves**.

![Snipaste_2024-10(10-28-14-13-12)](https://github.com/user-attachments/assets/d3429dc3-ec23-477d-aea2-51815590c637)

Could you share some design params of "A selection of design samples from our parametric garment template." in the paper, "GarmentCode: Programming Parametric Sewing Patterns".

![Snipaste_2024-10(10-28-14-13-12)(1)](https://github.com/user-attachments/assets/9e6182be-5892-4bb5-a388-a20c170a3f27)

**Comment by maria-korosteleva** [comment]
Thank you for your question! 

The garments in GarmentCode 2023 paper were created with the first version of the library. Both pattern parameters and `pygarment` library had changed by v2.0+, so the parameter sets for the garments in the paper have been removed

However, most parameters have the same semantic meaning as in the first release, so you can use the parameter files from v1.0.0 as a reference. You can find them here: [design parameters](https://github.com/maria-korosteleva/GarmentCode/tree/refs/tags/v1.0.0/assets/design_params). The dress you are looking for is called `modern_dress`. 

Overall, to achieve the puffy sleeves, you need 
1) the `connect_ruffle` parameter -- creates gathers on the shoulder side
2) Combination of `end_width` and `cuff`->`top_ruffle` -- to create gathers at the end of the sleeve. Some cuff should be chosen for it to work 

Hope this helps 😊

**Comment by LSQsjtu** [comment]
Thank you for your help. I have successfully achieved the desired puff sleeves following your instructions.
