### ISSUE TITLE
How can I add texture on the pattern?

### ISSUE THREAD

**Issue by MontaEllis** [maria-korosteleva/GarmentCode#24]
Good work! But how can I add texture on the pattern?

**Comment by maria-korosteleva** [comment]
Thank you!
Texturing is not the focus of this project, however, you can add texture to the simulated 3D models in the same way as texturing any other 3D object. The models have well-defined UV maps and we provide an example texture -- you can find it when you save the 3D models to files.

As for patterns themselves, you can use .svg file in any image editor of your choice and overlay it with your target image =)

**Comment by maria-korosteleva** [comment]
Please, reopen if you have follow-up questions
