### ISSUE TITLE
Using garment sewing patterns produced externally

### ISSUE THREAD

**Issue by TanJinxia** [maria-korosteleva/GarmentCode#25]
Hi! Is this possible to directly use a garment sewing pattern reconstructed from a 2D clothing image to reconstruct a 3D garment, or would I need to perform additional processing on sewing pattern? Thank you!

**Comment by maria-korosteleva** [comment]
Dear @TanJinxia, this project cannot reconstruct sewing patterns from images -- it's data generation work. All the valid sewing patterns generated with GarmentCode can be draped to get a corresponding 3D model, yes =)

**Comment by TanJinxia** [comment]
Thank you for your answer! If I utilise other projects to generate a sewing pattern from a 2D image. Can these sewing patterns be used to generate garments? are there format requirements for a sewing pattern?

**Comment by TanJinxia** [comment]
Thanks for replying, it helps me a lot!

**Comment by TanJinxia** [comment]
Dear @maria-korosteleva，I have reviewed the sewing patterns produced by another project, and I found that they are identical to those from your previous excellent project:   https://github.com/maria-korosteleva/Garment-Pattern-Generator/tree/master/data_generation/Patterns

And I have two questions:
	1.	Can these patterns be used in this new project, or would I need to make adjustments to ensure they fit into your new pipeline?
	2.	I noticed that your previous project used Maya for garment reconstruction. Can this new project replace Maya, or does it serve a different purpose?

**Comment by maria-korosteleva** [comment]
GarmentCode pipeline is backward compatible with the previous project and earlier version of JSON format :) So yes, you can go ahead and use your predictions here

We also still support Maya+Qualoth, you can find instruction on how to set it up in our documentation files

**Comment by TanJinxia** [comment]
That‘s great! Thank you!
