### ISSUE TITLE
how to measture a smplx body?

### ISSUE THREAD

**Issue by MontaEllis** [maria-korosteleva/GarmentCode#27]
I have a smplx body. How can I obtain the parameters in YAML format? Using GarmentMeasurements isn't working for me.

**Comment by maria-korosteleva** [comment]
@MontaEllis our automated measurement evaluation algorithms are designed for our custom statistical body model, shared in [GarmentMeasurements](https://github.com/mbotsch/GarmentMeasurements)

You can either use the bodies from our model or adapt the measurement evaluation code to work with SMPLX topology 

If you only need the measurements for a handful of bodies, you can also evaluate them manually

**Comment by maria-korosteleva** [comment]
All the code related to the body model is available in [GarmentMeasurements](https://github.com/mbotsch/GarmentMeasurements)
