### ISSUE TITLE
The JSON pattern differs between the PyGarment simulator and the Maya simulator.

### ISSUE THREAD

**Issue by MontaEllis** [maria-korosteleva/GarmentCode#28]
I found that the pattern generated from DressCode (a repository based on the Maya simulator) is incompatible with PyGarment.

![image](https://github.com/user-attachments/assets/fa69b779-8d64-497a-8f04-341e5575264f)

**Comment by MontaEllis** [comment]
Is there a method for making the transfer?

**Comment by maria-korosteleva** [comment]
The pattern definition is fully compatible, as in the example you provide the boxmesh was successfully generated. 
I see the issue with the alignment in the world coordinated, please, see my answer here: https://github.com/maria-korosteleva/GarmentCode/issues/26#issuecomment-2483924756 for the solution

Hope this helps!

**Comment by maria-korosteleva** [comment]
@MontaEllis as per the error you see, you pattern is not in the correct state geometry-wise, hence the mesh cannot be generated correctly. Please, check that your JSON files adhere to all the natural geometry constraints that come from our pattern definition: panel edges are forming a loop, all the edges references in the stitches actually exist, the stitches are 1-1 and each edge particiaptes only in once stitch, etc.
