### ISSUE TITLE
3D view doesn't refresh after upload and drape a new design

### ISSUE THREAD

**Issue by andrew-veriga** [maria-korosteleva/GarmentCode#29]
The second uploaded design and all subsequent ones don't change the 3d view what I generated at the first time on the connection. All processes are successfully completed and all tmp directories are updated normally and contained the new generated files, but the 3d view doesn't change since the first drape.
This bug isn't reproduced on demo https://garmentcode.ethz.ch/
I have installed the last version of both githubs and tuned my environment as described in [Environment Setup Notes #17](https://github.com/maria-korosteleva/GarmentCode/issues/17), but it is not help

**Comment by maria-korosteleva** [comment]
This is the issue with browser caching files with by file name instead of the content. For now you can manually clean the page cache to view the correct 3D model 

We know a workaround for it, and I will soon add it here too

**Comment by andrew-veriga** [comment]
Thank you for the fast reply

пн, 25 нояб. 2024 г. в 12:19, Maria Korosteleva ***@***.***>:

**Comment by maria-korosteleva** [comment]
Finally, I've pushed the fix: https://github.com/maria-korosteleva/GarmentCode/commit/e04ad9c015356aa7382f2a60eaa59735131b008a 
It should work now =)

**Comment by andrew-veriga** [comment]
Great! Thank you!

вт, 17 дек. 2024 г. в 14:03, Maria Korosteleva ***@***.***>:
