### ISSUE TITLE
body measurements

### ISSUE THREAD

**Issue by laviperepat** [maria-korosteleva/GarmentCode#6]
I am having trouble understanding the body measurements used, even given the inline documents. I cannot find reference of the measurements used in the given .yaml file in the literature for SMLP body. 
Is there a way to obtain these measurements from those that can be found from e.g. the meshcapade API, which I assume uses SMPL body model? e.g. how to obtain bum points, bust points, underbust, crotch_hip_diff, hips_line, bust_line, armscye_depth?

**Comment by maria-korosteleva** [comment]
Hi @laviperepat! The set of measurements used in GarmentCode is hand-crafted to meet the fitting needs of the parametric patterns and is not based on the existing sets of measurements for the SMPL body model. E.g. the measurements that Meshcapade API relies on are not enough to correctly fit the tailored bodice or pants. For the example body models used in the paper, we have taken the measurements manually using Autodesk Maya measuring tools. 

Thank you for pointing out that the documentation for the reference measurements is lacking. I will add a more detailed description as soon as I can.

**Comment by laviperepat** [comment]
Thanks! I would like to know what the measurements: `bum_points` and `crotch_hip_diff` mean and how to take them.

**Comment by maria-korosteleva** [comment]
Please, check the published [document](https://github.com/maria-korosteleva/GarmentCode/blob/main/docs/Body%20Measurements%20GarmentCode.pdf).
