### ISSUE TITLE
Issue with win32 on MacOS 

### ISSUE THREAD

**Issue by rahul-mitra13** [maria-korosteleva/GarmentCode#7]
Hey! I'm trying to install this codebase on a MacOS. 

After creating the conda environment and install all the dependencies, I run,

`python gui.py`

and I'm met with this error. 

```
(garmentcode) rahulmitra@crc-dot1x-nat-10-239-22-249 GarmentCode % python gui.py 
Traceback (most recent call last):
  File "/Users/rahulmitra/Desktop/GarmentCode/gui.py", line 9, in <module>
    from gui.callbacks import GUIState
  File "/Users/rahulmitra/Desktop/GarmentCode/./gui/callbacks.py", line 16, in <module>
    from assets.garment_programs.meta_garment import MetaGarment
  File "/Users/rahulmitra/Desktop/GarmentCode/./assets/garment_programs/meta_garment.py", line 8, in <module>
    import pygarment as pyg
  File "/Users/rahulmitra/Desktop/GarmentCode/./pygarment/__init__.py", line 5, in <module>
    from .component import Component
  File "/Users/rahulmitra/Desktop/GarmentCode/./pygarment/component.py", line 6, in <module>
    from pattern.wrappers import VisPattern
  File "/Users/rahulmitra/Desktop/GarmentCode/./external/pattern/wrappers.py", line 25, in <module>
    import customconfig
  File "/Users/rahulmitra/Desktop/GarmentCode/./external/customconfig.py", line 15, in <module>
    import wmi  # pip install wmi
  File "/Applications/anaconda3/envs/garmentcode/lib/python3.9/site-packages/wmi.py", line 88, in <module>
    from win32com.client import GetObject, Dispatch
ModuleNotFoundError: No module named 'win32com'
(garmentcode) rahulmitra@crc-dot1x-nat-10-239-22-249 GarmentCode % 
```
It seems as though I'm missing the win32 dependency.  After following [this] (https://stackoverflow.com/questions/23864234/importerror-no-module-named-win32com-client) SO thread, I tried

`pip install pypiwin32`

which was met with 

```
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl.metadata (236 bytes)
INFO: pip is looking at multiple versions of pypiwin32 to determine which version is compatible with other requirements. This could take a while.
  Using cached pypiwin32-219.zip (4.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kb/6990qqmd2sj_nhn82v1p3p980000gn/T/pip-install-guel9irk/pypiwin32_18095fa3abeb49619e4e7d8030312d57/setup.py", line 121
          print "Building pywin32", pywin32_version
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Building pywin32", pywin32_version)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

which seems like a classic case of python2 vs python3. Seems as though the syntax here for pypiwin32 is using python2 when I want to be using python3. If you've encountered this before, is there a work around you could suggest? Would appreciate any help, thanks!

**Comment by rahul-mitra13** [comment]
Did some more digging into pywin32 and it seems as though it's not installable on a MacOS? It shows up in the wmi dependency. Would appreciate any recommendations. Thanks again!

**Comment by maria-korosteleva** [comment]
Hi @rahul-mitra13 
Yes, you are correct, `wmi` is a Windows-specific library. I've set up conditions s.t. it only gets imported and used on Windows platforms [here](https://github.com/maria-korosteleva/GarmentCode/blob/6b33132194a77666a3fd54190323479696d2adc9/external/customconfig.py#L14) and [here](https://github.com/maria-korosteleva/GarmentCode/blob/6b33132194a77666a3fd54190323479696d2adc9/external/customconfig.py#L193)
  
On linux machines that condition works fine. However, I do not have devices with Mac OS, so I have not tested it there. I did some digging, and it seems like `platform.system()` returns 'Darwin' for MacOS which triggers the condition for 'win' check. 

I will fix it in the master, however, updating PyPi `pygarment` will take some time. Please, use the code from this repo directly once I add the fix =)

**Comment by rahul-mitra13** [comment]
Great, thank you for the fix!
